services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: radar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - radar_pg:/var/lib/postgresql/data

volumes:
  radar_pg:
